# Generated by Django 5.2.16 on 2026-07-17 15:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_backfill_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
