# Generated by Django 6.0.5 on 2026-05-31 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_restday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
